Epatient/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('app/', include('native.urls')),
    path('api/', include('api.urls')),
    path('', include('main.urls')),
    path('', include('accounts.urls')),
]

api/urls.py
from django.conf.urls import url
from rest_framework.authtoken.views import obtain_auth_token
from .views import CreateUserAPIView, LogoutUserAPIView, UserDashboard
from rest_framework_simplejwt import views as jwt_views
from native import views as nviews


urlpatterns = [
    url(r'^login/$', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    url(r'^refresh/$', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
    url(r'^register/$',
        CreateUserAPIView.as_view(),
        name='auth_user_create'),
    url(r'^logout/$',
        LogoutUserAPIView.as_view(),
        name='auth_user_logout'),
    url(r'^register/$',
        CreateUserAPIView.as_view(),
        name='auth_user_create'),
    url(r'^dashboard/$', nviews.index, name ='dashboard'),
]

main/urls.py
from django.urls import path,include
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index,name='index'),

    path('view-profile', views.view_profile,name='view_profile'),

    path('dashboard', views.dashboard,name='dashboard'),
############################################################ patient sites ################################
    path('incoming-appoint', views.incoming_appoint,name='incoming_appoint'),

    path('appointment/book', views.book,name='book'),
    path('search-doctors', views.searchDoctors,name='searchDoctors'),
    path('create-book', views.create_book,name='create_book'),

    path('appointment/view', views.view_book,name='view'),
    path('appoint-detail', views.appoint_detail,name='appoint_detail'),
    path('change-appoint', views.change_appoint,name='change_appoint'),
    path('cancel-appoint', views.cancel_appoint,name='cancel_appoint'),

    path('appointment/history', views.history,name='history'),
    path('appoint-history', views.appoint_history,name='appoint_history'),

    path('healthinfo/problems', views.problems,name='problems'),
    path('search-problems', views.search_problems,name='search_problems'),
    path('problems-detail', views.problems_detail,name='problems_detail'),

    path('healthinfo/medications', views.medications,name='medications'),
    path('search-medications', views.search_medications,name='search_medications'),
    path('medications-detail', views.medications_detail,name='medications_detail'),

    path('healthinfo/tests', views.tests,name='tests'),
    path('search-tests', views.search_tests,name='search_tests'),
    path('tests-detail', views.tests_detail,name='tests_detail'),

######################################################################################################
    path('incoming-requested', views.incoming_requested,name='incoming_requested'),
    path('appointment/requested-appoint', views.requested_appoint,name='requested_appoint'),
    path('appoint-detailform', views.appoint_detailform,name='appoint_detailform'),
    path('appoint-action', views.appoint_action,name='appoint_action'),

    path('patient-info', views.patient_info,name='patient_info'),

    path('save-problem', views.save_problem,name='save_problem'),
    path('create-problem', views.create_problem,name='create_problem'),

    path('save-medication', views.save_medication,name='save_medication'),
    path('create-medication', views.create_medication,name='create_medication'),

    path('save-test', views.save_test,name='save_test'),
    path('create-test', views.create_test,name='create_test'),

    path('healthinfo/users',views.user_info,name='user_info'),
    path('search-patients',views.search_patients,name='search_patients'),
    path('search-patients-name',views.search_patients_name,name='search_patients_name'),

    path('patient-info-user', views.patient_info_user,name='patient_info_user'),


###########################################################################################
    
    path('management/doctor', views.doctor,name='doctor'),
    path('management/patient', views.patient,name='patient'),
    path('search-doctors-birth',views.search_doctors_birth,name='search_doctors_birth'),
    path('search-doctors-name',views.search_doctors_name,name='search_doctors_name'),

    path('get-userinfo',views.get_userinfo,name='get_userinfo'),
    path('save-userinfo',views.save_userinfo,name='save_userinfo'),

    path('block-user',views.block_user,name='block_user'), # block user ajax
    path('add-doctor',views.add_doctor,name='add_doctor'), # add user ajax

    path('add-patient',views.add_patient,name='add_patient'), # add user ajax

    path('patient-info-user-admin', views.patient_info_user_admin,name='patient_info_user_admin'),
    path('change-password', views.change_password,name='change_password'),
]

main/models.py
from django.db import models

# Create your models here.
from datetime import date


class Appointment(models.Model):
    PENDING = 'P'
    ACCEPTED = 'A'
    REJECTED = 'R'
    STATUS_CHOICES = (
        (PENDING, 'pending'),
        (ACCEPTED,'accepted'),
        (REJECTED,'rejected'),
    )

    user_id = models.IntegerField()
    doctor_id = models.IntegerField()
    book_date = models.DateField()
    from_time = models.TimeField()
    to_time=models.TimeField()
    limit_date = models.DateTimeField(null=True,blank=True)
    book_text = models.TextField()
    status = models.CharField(max_length = 2, choices = STATUS_CHOICES, default = PENDING)
    pub_date = models.DateTimeField(auto_now_add=True)

class Problem(models.Model):
    user_id = models.IntegerField()
    description = models.TextField()
    pub_date = models.DateField(auto_now_add=True)

class Medication(models.Model):
    ACUTE = 'A'
    REPEAT = 'R'
    STATUS_CHOICES = (
        (ACUTE, 'acute'),
        (REPEAT,'repeat'),
    )
    user_id = models.IntegerField()
    doctor_id = models.IntegerField()
    description = models.TextField()
    status = models.CharField(max_length = 2, choices = STATUS_CHOICES, default = ACUTE)
    pub_date=models.DateField(auto_now_add=True)

class Test(models.Model):                   #Test model
    user_id = models.IntegerField()
    doctor_id = models.IntegerField()
    name = models.CharField(max_length = 50)
    description = models.TextField()
    result = models.CharField(max_length = 200)
    pub_date=models.DateField(auto_now_add=True)
    

    
    

main/views.py
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.core import serializers
from django.contrib.auth.hashers import make_password

from accounts.models import User
from main.models import Appointment,Problem,Medication, Test
from django.db.models import Q
from datetime import datetime, timedelta
from dateutil.relativedelta import relativedelta
import json


def index(request):
    return render(request, 'index.html')

def view_profile(request):
    useremail = request.session['useremail']
    user = User.objects.filter(useremail = useremail)
    if user:
        serialized_queryset = serializers.serialize('json', user)
        return HttpResponse(json.dumps(serialized_queryset),content_type="application/json")
    return HttpResponse(json.dumps(""),content_type="application/json")



def dashboard(request):
    user = User.objects.get(useremail = request.session['useremail'])
    request.session['username'] = user.first_name + " "+ user.last_name
    if user.user_type == 'PA':
        return render(request, 'native/front-pagec.html', {'user': user})
    elif user.user_type == 'MD':
        return render(request, 'main/medical/dashboard.html', {'user': user})
    elif user.user_type == 'AD':
        return render(request, 'main/admin/dashboard.html', {'user': user})

#get incoming appointments for this week
def incoming_appoint(request):
    time_threshold = datetime.now()+timedelta(days=6)
    useremail = request.session['useremail']
    user = User.objects.get(useremail = useremail)
    accept_appoints = Appointment.objects.filter(user_id = user.id).filter(status='A').filter(limit_date__gt = datetime.now()).filter(limit_date__lt=time_threshold)
    if len(accept_appoints) > 0:
        serialized_queryset = serializers.serialize('json', accept_appoints)
        return HttpResponse(json.dumps(serialized_queryset),content_type="application/json")
    return HttpResponse(json.dumps(""),content_type="application/json")

def book(request):
    return render(request,'main/patient/book.html')

#search available doctors for selected period
def searchDoctors(request):
    pick_date = request.GET['date']
    b_date = datetime.strptime(pick_date,'%Y-%m-%d')
    fromString = request.GET['from']
    toString = request.GET['to']
    fromArray = fromString.split('-')
    toArray = toString.split('-')
    fromHour = 0
    toHour = 0
    if fromArray[1] == 'PM':
        fromHour = 12 + int(fromArray[0])
    else:
        fromHour = int(fromArray[0])
    if toArray[1] == 'PM':
        toHour = 12 + int(toArray[0])
    else:
        toHour = int(toArray[0])
    begin = datetime.strptime(str(fromHour)+":"+fromArray[2], '%H:%M').time()
    end = datetime.strptime(str(toHour)+":"+toArray[2], '%H:%M').time()
    doctors = Appointment.objects.filter(status='A').filter(Q(book_date=b_date))
    doctors1 = doctors.filter(Q(from_time__lt=begin)).filter(Q(to_time__gt=begin))
    doctors2 = doctors.filter(Q(from_time__lt=end)).filter(Q(to_time__gt=end))

    users = User.objects.filter(is_active=True).filter(user_type ='MD')
    av_doctors = []
    for user in users:
        flag = 0
        for doctor in doctors1:
            if user.id == doctor.doctor_id:
                flag = 1
        for doctor in doctors2:
            if user.id == doctor.doctor_id:
                flag = 1
        if flag == 0:
            av_doctors.append(user)
    serialized_queryset = serializers.serialize('json', av_doctors)
    return HttpResponse(json.dumps(serialized_queryset),content_type="application/json")

#create one book(appointment)        
def create_book(request):
    response = {}
    try:
        doctor_pk = request.GET['pk']
        book_text = request.GET['book_text']
        pick_date = request.GET['date']
        b_date = datetime.strptime(pick_date,'%Y-%m-%d')
        fromString = request.GET['from']
        toString = request.GET['to']
        fromArray = fromString.split('-')
        toArray = toString.split('-')
        fromHour = 0
        toHour = 0
        if fromArray[1] == 'PM':
            fromHour = 12 + int(fromArray[0])
        else:
            fromHour = int(fromArray[0])
        if toArray[1] == 'PM':
            toHour = 12 + int(toArray[0])
        else:
            toHour = int(toArray[0])
        begin = datetime.strptime(str(fromHour)+":"+fromArray[2], '%H:%M').time()
        end = datetime.strptime(str(toHour)+":"+toArray[2], '%H:%M').time()
        end_date = datetime.strptime(pick_date+"-"+str(fromHour)+":"+fromArray[2],'%Y-%m-%d-%H:%M')
        print(end_date)

        user = User.objects.get(useremail = request.session['useremail'])
        appoint = Appointment(user_id = user.id,doctor_id=doctor_pk,book_date=pick_date,from_time=begin,to_time = end,book_text=book_text,limit_date=end_date)
        appoint.save()
        response['status'] = "success"
    except Exception:
        response['status'] = "error"
    return HttpResponse(json.dumps(response),content_type="application/json")


# get accepted, pending, expired, rejected appointments for 6 days from now
def view_book(request):
    time_threshold = datetime.now()-timedelta(days=6)
    accept_appoints = Appointment.objects.filter(status='A').filter(limit_date__gt=time_threshold)
    pending_appoints = Appointment.objects.filter(status='P').filter(limit_date__gt=time_threshold)
    reject_appoints = Appointment.objects.filter(status='R').filter(limit_date__gt=time_threshold)
    
#    time = datetime.strptime(datetime.datetime.today().strftime('%H:%M'))
    real_pending_appoints = pending_appoints.filter(limit_date__gte = datetime.now())
    expired_appoints = pending_appoints.filter(limit_date__lt=datetime.now())

    print(accept_appoints)
    print(real_pending_appoints)
    print(expired_appoints)
    print(reject_appoints)

    return render(request,"main/patient/view_book.html",{'accepted':accept_appoints,'pending':real_pending_appoints,'rejected':reject_appoints,'expired':expired_appoints})

#get details for selected appointment
def appoint_detail(request):
    try:
        appoint = Appointment.objects.get(id=request.GET['pk'])
        doctor_id = appoint.doctor_id
        doctor = User.objects.get(id = doctor_id)

        response = {}
        response['doctor'] = doctor.first_name + " " + doctor.last_name
        response['pub_date'] = appoint.pub_date.strftime('%Y-%m-%d %H:%M')
        response['text'] = appoint.book_text
    except Exception:
        response['doctor'] = 'error'
    return HttpResponse(json.dumps(response),content_type="application/json")

#change appointment text for selected appointment
def change_appoint(request):
    try:
        response = {}
        appoint = Appointment.objects.get(id=request.GET['pk'])
        appoint.book_text = request.GET['book_text']
        appoint.save()
        response['status'] = 'success'
    except Exception:
        response['status'] = 'error'
    return HttpResponse(json.dumps(response),content_type="application/json")

#cnacel pending appointment
def cancel_appoint(request):
    try:
        response = {}
        appoint = Appointment.objects.get(id=request.GET['pk'])
        appoint.delete()
        response['status'] = 'success'
    except Exception:
        response['status'] = 'error'
    return HttpResponse(json.dumps(response),content_type="application/json")

def history(request):
    return render(request,"main/patient/history_book.html")

#get all appointment for selected date
def appoint_history(request):
    now  = datetime.now()
    first_day = datetime(int(request.GET['year']),int(request.GET['month']),1,0,0,0)
    end_day = first_day+relativedelta(months=+1)
    end_day = end_day - timedelta(days=1)
    appoints = Appointment.objects.filter(limit_date__gte = first_day).filter(limit_date__lte = end_day)
    if len(appoints) > 0:
        serialized_queryset = serializers.serialize('json', appoints)
        return HttpResponse(json.dumps(serialized_queryset),content_type="application/json")
    return HttpResponse(json.dumps(""),content_type="application/json")
        
def problems(request):
    return render(request,"main/patient/problems.html")

#get problems for selected month
def search_problems(request):
    now  = datetime.now()
    first = datetime(int(request.GET['year']),int(request.GET['month']),1,0,0,0)
    end = first+relativedelta(months=+1)
    end = end - timedelta(days=1)

    problems = Problem.objects.filter(pub_date__gte = first).filter(pub_date__lte = end)
    print(problems)
    if len(problems) > 0:
        serialized_queryset = serializers.serialize('json', problems)
        return HttpResponse(json.dumps(serialized_queryset),content_type="application/json")
    return HttpResponse(json.dumps(""),content_type="application/json")

#get details for selected problem        
def problems_detail(request):
    response = {}
    try:
        pk = request.GET['pk']
        problem = Problem.objects.get(id=pk)
        doctor_id = problem.doctor_id
        doctor = User.objects.get(id=doctor_id)
        response['doctor'] = doctor.first_name + " " + doctor.last_name
        response['pub_date'] = problem.pub_date.strftime('%Y-%m-%d')
        response['description'] = problem.description
    except Exception:
        response['doctor'] = 'error'
    return HttpResponse(json.dumps(response),content_type="application/json")


def medications(request):
    return render(request,"main/patient/medications.html")

#get medications for selected month
def search_medications(request):

    now  = datetime.now()
    first = datetime(int(request.GET['year']),int(request.GET['month']),1,0,0,0)
    end = first+relativedelta(months=+1)
    end = end - timedelta(days=1)

    medications = Medication.objects.filter(pub_date__gte = first).filter(pub_date__lte = end)
    if len(medications) > 0:
        serialized_queryset = serializers.serialize('json', medications)

content/templates/main/patient/view_book.html
{% extends 'layouts/patient/main.html' %} 
{% load static %}
{% block content %}
<div class="container-fluid">
    <div class="row">
            <div class="col-12">

                <h1>View Appointments</h1>
                <nav class="breadcrumb-container d-none d-sm-block d-lg-inline-block" aria-label="breadcrumb">
                    <ol class="breadcrumb pt-0">
                        <li class="breadcrumb-item">
                            <a href="#">Appointment</a>
                        </li>
                        <li class="breadcrumb-item">
                            <a href="#">View</a>
                        </li>
                    </ol>
                </nav>
                <div class="separator mb-5"></div>
            </div>
        <div class="col-12 col-xl-6 mb-4">
            <div class="card h-100">
                <div class="card-body" style="overflow-y: auto; overflow-y:scroll; max-height: 300px">
                    <h4>Accepted Appointments</h4>
                    <div class="separator"></div>
                    {% for model in accepted %}
                    <div class="mb-4">
                        <br>
                        <a onclick="viewAppoint({{model.pk}})" style="cursor:pointer">
                            <p class="list-item-heading mb-1 color-theme-1">{{model.book_date}} </p>
                            <p class="mb-1 text-muted text-small">accepted</p>
                            <p class="mb-4 text-small">{{model.from_time}} - {{model.to_time}}</p>
                        </a>
                        <div class="separator"></div>
                    </div>

                    {% endfor %}
                    
                </div>
            </div>
        </div>
        
        <div class="col-12 col-xl-6 mb-4">
            <div class="card h-100">
                <div class="card-body" style="overflow-y: auto; overflow-y:scroll; max-height: 300px">
                    <h4>Pending Appointments</h4>
                    <div class="separator"></div>
                    {% for model in pending %}
                    <div class="mb-4">
                        <br>
                        <div class="row">
                            <div class="col-md-10">
                                <a onclick="viewPAppoint({{model.pk}})" style="cursor:pointer">
                                    <p class="list-item-heading mb-1 color-theme-1">{{model.book_date}} </p>
                                    <p class="mb-4 text-small">{{model.from_time}} - {{model.to_time}}</p>
                                </a>
                            </div>
                            <div class="col-md-2">
                                <button class="btn btn-danger btn-xs mb-1" onclick="cancelBook({{model.pk}})">cancel</button>
                            </div>
                        </div>
    
                        <div class="separator"></div>
                    </div>
                    {% endfor %}
                    
                </div>
            </div>
        </div>
    
        <div class="col-12 col-xl-6 mb-4">
                <div class="card h-100">
                    <div class="card-body" style="overflow-y: auto; overflow-y:scroll; max-height: 300px">
                        <h4>Rejected Appointments</h4>
                        <div class="separator"></div>
                        {% for model in rejected %}
                        <div class="mb-4">
                            <br>
                            <a onclick="viewAppoint({{model.pk}})" style="cursor:pointer">
                                <p class="list-item-heading mb-1 color-theme-1">{{model.book_date}} </p>
                                <p class="mb-1 text-muted text-small">accepted</p>
                                <p class="mb-4 text-small">{{model.from_time}} - {{model.to_time}}</p>
                            </a>
                            <div class="separator"></div>
                        </div>
    
                        {% endfor %}
                        
                    </div>
                </div>
            </div>
    

            <div class="col-12 col-xl-6 mb-4">
                <div class="card h-100">
                    <div class="card-body" style="overflow-y: auto; overflow-y:scroll; max-height: 300px">
                        <h4>Expired Appointments</h4>
                        <div class="separator"></div>   
                        {% for model in expired %}
                        <div class="mb-4">
                            <br>
                            <a onclick="viewAppoint({{model.pk}})" style="cursor:pointer">
                                <p class="list-item-heading mb-1 color-theme-1">{{model.book_date}} </p>
                                <p class="mb-1 text-muted text-small">accepted</p>
                                <p class="mb-4 text-small">{{model.from_time}} - {{model.to_time}}</p>
                            </a>
                            <div class="separator"></div>
                        </div>
    
                        {% endfor %}
                        
                    </div>
                </div>
            </div>
    

        <!-- booking modal -->

        <div class="modal fade" id="bookModal" tabindex="-1" role="dialog" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalContentLabel">Appointment Details</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <div class="form-group">
                                <label for="message-text" class="col-form-label"><b>Doctor Name:</b></label>
                                <span id="doctorName"></span>
                            </div>
                            <div class="form-group">
                                <label for="message-text" class="col-form-label"><b>Created Date:</b></label>
                                <span id="createdDate"></span>
                            </div>
                            <div class="form-group">
                                <label for="message-text" class="col-form-label"><b>Book Text</b></label>
                                <textarea class="form-control" id="book-text" readonly></textarea>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </div>

        <!-- modal end -->


        <!-- booking modal -->

        <div class="modal fade" id="pendingModal" tabindex="-1" role="dialog" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalContentLabel">Appointment Details</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <input type="hidden" id="curPK">
                            <div class="form-group">
                                <label for="message-text" class="col-form-label"><b>Doctor Name:</b></label>
                                <span id="pdoctorName"></span>
                            </div>
                            <div class="form-group">
                                <label for="message-text" class="col-form-label"><b>Created Date:</b></label>
                                <span id="pcreatedDate"></span>
                            </div>
                            <div class="form-group">
                                <label for="message-text" class="col-form-label"><b>Book Text</b></label>
                                <textarea class="form-control" id="pbook-text"></textarea>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-primary" onclick="changeAppoint()">Save</button>
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </div>

        <!-- modal end -->




    </div>
</div>

<script>

    // display details for selected appointment
    function viewAppoint(pk){
        $("#doctorName").text("");
        $("#createdDate").text("");
        $("#book-text").val("");
        $("#bookModal").modal();
        $.ajax({
            type: "GET",
            url: "{% url 'main:appoint_detail' %}",
            data: {pk:pk},
            dataType: 'json',
            success: function (data) {
                if(data.doctor != "error"){
                    $("#doctorName").text(data.doctor);
                    $("#createdDate").text(data.pub_date);
                    $("#book-text").val(data.text);

                }else{
                    $.sweetModal({
                        content: 'error happened!.',
                        icon: $.sweetModal.ICON_ERROR,
                        buttons: [
                            {
                                label: 'That\'s fine',
                                classes: 'redB'
                            }
                        ]                        
                    });

                }
            }
        });
    }

    // display details for selected appointment
    function viewPAppoint(pk){
        $("#pdoctorName").text("");
        $("#pcreatedDate").text("");
        $("#pbook-text").val("");
        $("#pendingModal").modal();
        $("#curPK").val(pk);
        $.ajax({
            type: "GET",
            url: "{% url 'main:appoint_detail' %}",
            data: {pk:pk},
            dataType: 'json',
            success: function (data) {
                if(data.doctor != "error"){
                    $("#pdoctorName").text(data.doctor);
                    $("#pcreatedDate").text(data.pub_date);
                    $("#pbook-text").val(data.text);

                }else{
                    $.sweetModal({
                        content: 'error happened!.',
                        icon: $.sweetModal.ICON_ERROR,
                        buttons: [
                            {
                                label: 'That\'s fine',
                                classes: 'redB'
                            }
                        ]                        
                    });

                }
            }
        });
    }


    // change appointment text 
    function changeAppoint(){
        var pk = $("#curPK").val();
        var text = $("#pbook-text").val();

        $.ajax({
            type: "GET",
            url: "{% url 'main:change_appoint' %}",
            data: {pk:pk,book_text:text},
            dataType: 'json',
            success: function (data) {
                if(data.doctor == "error"){
                    $.sweetModal({
                        content: 'error happened!.',
                        icon: $.sweetModal.ICON_ERROR,
                        buttons: [
                            {
                                label: 'That\'s fine',
                                classes: 'redB'
                            }
                        ]                        
                    });
                }
            }
        });

        $("#pendingModal").modal('toggle');

    }


// cancel pending appointment.
    function cancelBook(pk){
        $.sweetModal.confirm('Confirm please?', function() {
            $.ajax({
            async:false,
            type: "GET",
            url: "{% url 'main:cancel_appoint' %}",
            data: {pk:pk},
            dataType: 'json',
            success: function (data) {
                if(data.doctor == "error"){
                    $.sweetModal({
                        content: 'error happened!.',
                        icon: $.sweetModal.ICON_ERROR,
                        buttons: [
                            {
                                label: 'That\'s fine',
                                classes: 'redB'
                            }
                        ]                        
                    });
                }
            }
        });
        location.reload();

        });


    }


</script>
{% endblock %}